# -*- coding: utf-8 -*-
"""ppn2v_runner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKpK2i9PnCQrobW921T56jXk7z55c_4o
"""

from google.colab import drive
drive.mount('/content/drive')

DRIVE_ROOT = "/content/drive/MyDrive"
DATA_DIR   = f"{DRIVE_ROOT}/ppn2v_data"
MODELS_DIR = f"{DRIVE_ROOT}/ppn2v_models"
RUNS_DIR   = f"{DRIVE_ROOT}/ppn2v_runs"

import os
for p in [DATA_DIR, MODELS_DIR, RUNS_DIR]:
    os.makedirs(p, exist_ok=True)

print("DATA  :", DATA_DIR)
print("MODELS:", MODELS_DIR)
print("RUNS  :", RUNS_DIR)

!rm -rf /content/repo
!git clone https://github.com/ZurvanAkarna/PPN2V.git /content/repo

!ls /content/repo/src/ppn2v

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/repo
!pwd

!python -m pip install -e .

!python -m pip show ppn2v

import ppn2v
import ppn2v.pn2v
print("PPN2V import OK")

!ls /content/repo
!ls /content/repo/src/ppn2v

import src.ppn2v

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/repo
!pip install -e .

import sys
sys.path.append('/content/repo/src')

import src.ppn2v
print("PPN2V import OK")

!pip install -e /content/repo